#!/usr/bin/env bash

# Function to switch to FiiO K7
headphones () {
  SINK="alsa_output.usb-GuangZhou_FiiO_Electronics_Co._Ltd_FiiO_K7-00.analog-stereo"
  pactl set-default-sink "$SINK"
  for INPUT in $(pactl list short sink-inputs | awk '{print $1}'); do
    pactl move-sink-input "$INPUT" "$SINK"
  done
  notify-send -h string:bgcolor:#a3be8c "Audio switched to headphones!"
}

# Function to switch to HDMI output
speakers () {
  SINK="alsa_output.pci-0000_01_00.1.hdmi-stereo"
  pactl set-default-sink "$SINK"
  for INPUT in $(pactl list short sink-inputs | awk '{print $1}'); do
    pactl move-sink-input "$INPUT" "$SINK"
  done
  notify-send -h string:bgcolor:#bf616a "Audio switched to speakers!"
}
# Menu to choose output
choosespeakers() {
  choice=$(printf "Headphones\nSpeakers" | fuzzel --dmenu --prompt "Choose output: ")
  case "$choice" in
    Headphones) headphones ;;
    Speakers) speakers ;;
  esac
}

choosespeakers
