#!/usr/bin/env bash
folder=$HOME/notes/

newnote() {
    name="$(echo "" | fuzzel --dmenu --prompt "Enter a name: " --width 40 --lines 1)" || exit 0
    : "${name:=$(date +%F_%T | tr ':' '-')}"
    setsid -f "$TERMINAL" -e nvim "$folder$name.md" >/dev/null 2>&1
}

selected() {
    choice=$(echo -e "New\n$(command ls -t1 $folder 2>/dev/null)" | fuzzel --dmenu --prompt "Choose note or create new: " --lines 10 --width 50)
    
    case $choice in
        New) newnote ;;
        *.md) setsid -f "$TERMINAL" -e nvim "$folder$choice" >/dev/null 2>&1 ;;
        "") exit 0 ;;  # Handle Escape/Ctrl+C
        *) exit ;;
    esac
}

selected