dpi-aware=yes
icon-theme=Adwaita
width=200
font=FiraCode Nerd Font:size=12
line-height=25
fields=name,generic,comment,categories,filename,keywords
terminal=wezterm -e
prompt="❯ "
#show-actions=yes
exit-on-keyboard-focus-loss=no

[colors]
background=232136ff
selection= 44415aff
border=232136ff
text=e0def4ff
input=e0def4ff
prompt=e0def4ff
selection-text=e0def4ff

[dmenu]
exit-immediately-if-empty=yes
