## Wofi Config

## General
show=drun
prompt=Wallpapers
normal_window=true

## Geometry
width=40%
height=30%


## Images
allow_markup=true
allow_images=true
image_size=200

## Search
exec_search=false
hide_search=false
parse_search=false
insensitive=false

## Other
gtk_dark=true

## Keys
key_expand=Tab
key_exit=Escape

