@define-color foreground #F3F9E5;
@define-color background alpha(#1F2321,0.05);
@define-color cursor #9EBEAD;

@define-color color0 #444947;
@define-color color1 #637782;
@define-color color2 #488274;
@define-color color3 #998C1D;
@define-color color4 #8E9181;
@define-color color5 #91BC9B;
@define-color color6 #DDEFB5;
@define-color color7 #E6EFD2;
@define-color color8 #A1A793;
@define-color color9 #637782;
@define-color color10 #488274;
@define-color color11 #998C1D;
@define-color color12 #8E9181;
@define-color color13 #91BC9B;
@define-color color14 #DDEFB5;
@define-color color15 #E6EFD2;