backend = "resized"
threshold = 10
palette = "dark"

[templates]
ghostty.template = 'colors-ghostty.conf'
ghostty.target = "/home/polaris/.dotfiles/.config/ghostty/wallust.conf"

hypr.template = 'colors-hypr.conf'
hypr.target = '/home/polaris/.dotfiles/.config/hypr/colors-hypr.conf'