background = "#2D2625"
foreground = "#E0E9EF"
selection-background = "#CAD8DF"
selection-foreground = "#2D2625"
cursor-color = "#ACBED4"

# Normal colors
palette = 0=#534B4A
palette = 1=#87918D
palette = 2=#7992B9
palette = 3=#D1A070
palette = 4=#B9A6A3
palette = 5=#BAB899
palette = 6=#A6C1D0
palette = 7=#CAD8DF

# Bright colors
palette = 8=#8D979C
palette = 9=#87918D
palette = 10=#7992B9
palette = 11=#D1A070
palette = 12=#B9A6A3
palette = 13=#BAB899
palette = 14=#A6C1D0
palette = 15=#CAD8DF