background = "#1F2321"
foreground = "#F3F9E5"
selection-background = "#E6EFD2"
selection-foreground = "#1F2321"
cursor-color = "#9EBEAD"

# Normal colors
palette = 0=#444947
palette = 1=#637782
palette = 2=#488274
palette = 3=#998C1D
palette = 4=#8E9181
palette = 5=#91BC9B
palette = 6=#DDEFB5
palette = 7=#E6EFD2

# Bright colors
palette = 8=#A1A793
palette = 9=#637782
palette = 10=#488274
palette = 11=#998C1D
palette = 12=#8E9181
palette = 13=#91BC9B
palette = 14=#DDEFB5
palette = 15=#E6EFD2