background = "#1B1F1F"
foreground = "#C2F8FB"
selection-background = "#9FECF1"
selection-foreground = "#1B1F1F"
cursor-color = "#B7D2BC"

# Normal colors
palette = 0=#414645
palette = 1=#80B1A3
palette = 2=#ACAC7C
palette = 3=#4EB5DC
palette = 4=#A7C92E
palette = 5=#E7B75E
palette = 6=#50EAF4
palette = 7=#9FECF1

# Bright colors
palette = 8=#6FA5A9
palette = 9=#80B1A3
palette = 10=#ACAC7C
palette = 11=#4EB5DC
palette = 12=#A7C92E
palette = 13=#E7B75E
palette = 14=#50EAF4
palette = 15=#9FECF1