$wallpaper = /home/polaris/Documents/wallpapers/grass_fields.jpg
$background = rgb(1F2321)
$foreground = rgb(F3F9E5)
$color0 = rgb(444947)
$color1 = rgb(637782)
$color2 = rgb(488274)
$color3 = rgb(998C1D)
$color4 = rgb(8E9181)
$color5 = rgb(91BC9B)
$color6 = rgb(DDEFB5)
$color7 = rgb(E6EFD2)
$color8 = rgb(A1A793)
$color9 = rgb(637782)
$color10 = rgb(488274)
$color11 = rgb(998C1D)
$color12 = rgb(8E9181)
$color13 = rgb(91BC9B)
$color14 = rgb(DDEFB5)
$color15 = rgb(E6EFD2)