$wallpaper = /home/polaris/Documents/wallpapers/morning_in_a_pine_forest.png
$background = rgb(1B1A1B)
$foreground = rgb(F9F8D4)
$color0 = rgb(424142)
$color1 = rgb(5D93B7)
$color2 = rgb(A18E6D)
$color3 = rgb(83978A)
$color4 = rgb(AABBC7)
$color5 = rgb(CDDBC5)
$color6 = rgb(EFEC85)
$color7 = rgb(EFEDBA)
$color8 = rgb(A7A682)
$color9 = rgb(5D93B7)
$color10 = rgb(A18E6D)
$color11 = rgb(83978A)
$color12 = rgb(AABBC7)
$color13 = rgb(CDDBC5)
$color14 = rgb(EFEC85)
$color15 = rgb(EFEDBA)