$wallpaper = /home/polaris/Documents/wallpapers/aquarium.png
$background = rgb(1B1F1F)
$foreground = rgb(C2F8FB)
$color0 = rgb(414645)
$color1 = rgb(80B1A3)
$color2 = rgb(ACAC7C)
$color3 = rgb(4EB5DC)
$color4 = rgb(A7C92E)
$color5 = rgb(E7B75E)
$color6 = rgb(50EAF4)
$color7 = rgb(9FECF1)
$color8 = rgb(6FA5A9)
$color9 = rgb(80B1A3)
$color10 = rgb(ACAC7C)
$color11 = rgb(4EB5DC)
$color12 = rgb(A7C92E)
$color13 = rgb(E7B75E)
$color14 = rgb(50EAF4)
$color15 = rgb(9FECF1)