source = ~/.dotfiles/.config/hypr/colors-hypr.conf
source = ~/.dotfiles/.config/hypr/config/monitors.conf
source = ~/.dotfiles/.config/hypr/config/auto-start.conf
source = ~/.dotfiles/.config/hypr/config/env.conf
source = ~/.dotfiles/.config/hypr/config/theme.conf
source = ~/.dotfiles/.config/hypr/config/input.conf
source = ~/.dotfiles/.config/hypr/config/window-rules.conf


debug {
disable_logs = false
enable_stdout_logs = true
} 
