
source = ~/.dotfiles/.config/hypr/config/windows.conf
source = ~/.dotfiles/.config/hypr/config/monitors.conf
source = ~/.dotfiles/.config/hypr/config/autostart.conf
source = ~/.dotfiles/.config/hypr/config/env.conf
source = ~/.dotfiles/.config/hypr/config/theme.conf
source = ~/.dotfiles/.config/hypr/config/input.conf

