preload = ~/.dotfiles/.config/hypr/wallpapers/grass_fields.jpg
preload = ~/.dotfiles/.config/hypr/wallpapers/morning_in_a_pine_forest.png

wallpaper = ,~/.dotfiles/.config/hypr/wallpapers/morning_in_a_pine_forest.png

