[[mgr.prepend_keymap]]
on = ["g", "c"]
run = 'cd ~/projects/cozynet'
desc = "Go to cozynet"

[[mgr.prepend_keymap]]
on = ["g", "h"]
run = 'cd ~/'
desc = "Go home"

[[mgr.prepend_keymap]]
on = ["g", "t"]
run = 'cd ~/temp'
desc = "Go to temp"

[[mgr.prepend_keymap]]
on = ["g", "d"]
run = 'cd ~/dotfiles'
desc = "Go to dotfiles"

[[mgr.prepend_keymap]]
on = ["<C-o>"]
run = 'back'
desc = "Back in history"

[[mgr.prepend_keymap]]
on = ["<C-i>"]
run = 'forward'
desc = "Forward in history"