bind_to_address "127.0.0.1"
 #bind_to_address "~/.mpd/socket"
 music_directory "/home/polaris/nas/music"
 playlist_directory "~/.dotfiles/.config/mpd/playlists"   
 db_file      "~/.dotfiles/.config/mpd/mpd.db"  
 log_file      "~/.dotfiles/.config/mpd/mpd.log"  
 pid_file      "~/.dotfiles/.config/mpd/mpd.pid"  
 state_file     "~/.dotfiles/.config/mpd/mpdstate"
   
audio_output {
        type            "pulse"
        name            "ALSA/PulseAudio"
}

#  systemctl --user enable mpd and started it with systemctl --user start mpd enable and start as user never root