[manager]
prepend_keymap = [
    { on = ["g", "h"], run = 'cd ~', desc = "go home" },
    { on = ["g", "c"], run = 'cd ~/dotfiles', desc = "go to dotfiles" },
		{ on = ["g", "s"], run = 'cd ~/projects/sega/', desc = "go to dotfiles" },
    { on = ["g", "w"], run = 'cd ~/projects/work/', desc = "go to dotfiles" },

]

