exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store
exec-once = hyprpaper &
exec-once = swaync &
exec-once =  waybar -c ~/.config/waybar/config-left.json &
exec-once =  waybar -c ~/.config/waybar/config-right.json &
exec-once = systemctl --user start hyprpolkitagent 