# Keep your existing exec-once commands
exec-once = sleep 3; ironbar load-css ~/.dotfiles/.config/ironbar/colors-ironbar.css
exec-once = hyprpaper 
exec-once = swaync
exec-once = systemctl --user start hyprpolkitagent

exec-once = [workspace 1 silent] zen-browser
exec-once = [workspace 2 silent] steam
exec-once = [workspace 6 silent] vesktop
exec-once = [workspace 7 silent] tauon

# Make sure these programs launch in their workspaces
windowrule = workspace 1 silent, class:zen
windowrule = workspace 2 silent, class:steam
windowrule = workspace 6 silent, class:vesktop
windowrule = workspace 7 silent, class:tauon

windowrule = float, class:waypaper
