# Keep your existing exec-once commands
exec-once = waybar 
exec-once = hyprpaper 
exec-once = swaync
exec-once = systemctl --user start hyprpolkitagent

exec-once = [workspace 1 silent] zen-browser
exec-once = [workspace 2 silent] vesktop
exec-once = [workspace 3 silent] steam
exec-once = [workspace 4 silent] wezterm -e rmpc

# Make sure these programs launch in their workspaces
windowrule = workspace 1 silent, class:zen
windowrule = workspace 2 silent, class:vesktop
windowrule = workspace 3 silent, class:steam


# Fixes
windowrule = tile, title:^(Unnamed build \(Scion\) - Path of Building)$
windowrule = float, class:waypaper
