################
### MONITORS ###
################
# monitor2 = desc:Samsung Electric Company Odyssey G5 HNBY100250
$monitor1 = desc:Acer Technologies KG271U TATAA0028524

# Basic monitor setup
monitor = $monitor1, 2560x1440@180, 0x0, 1
# monitor = $monitor2, 2560x1440@144, 2560x0, 1


# Default workspaces for monitors
workspace = 1, monitor:$monitor1
workspace = 2, monitor:$monitor1
workspace = 3, monitor:$monitor1
workspace = 4, monitor:$monitor1
workspace = 5, monitor:$monitor1
# workspace = 6, monitor:$monitor2
# workspace = 7, monitor:$monitor2
# workspace = 8, monitor:$monitor2
# workspace = 9, monitor:$monitor2
# workspace = 10, monitor:$monitor2

# Set default workspaces on startup
exec-once = hyprctl dispatch focusmonitor $monitor1
exec-once = hyprctl dispatch workspace 1
# exec-once = hyprctl dispatch focusmonitor $monitor2 
# exec-once = hyprctl dispatch workspace 6
