################
### MONITORS ###
################

$monitor1 = desc:Samsung Electric Company Odyssey G5 HNBY100250
$monitor2 = desc:Acer Technologies KG271U TATAA0028524

monitor = $monitor1, 2560x1440@180, 0x0, 1
monitor = $monitor2, 2560x1440@144, 2560x0, 1

workspace = 1, $monitor1
workspace = 2, $monitor1
workspace = 3, $monitor1
workspace = 4, $monitor1
workspace = 5, $monitor1

workspace = 6, $monitor2
workspace = 7, $monitor2
workspace = 8, $monitor2
workspace = 9, $monitor2
workspace = 10, $monitor2
