################
### MONITORS ###
################
$monitor1 = desc:Samsung Electric Company Odyssey G5 H1AK500000
$monitor2 = desc:Acer Technologies KG271U TATAA0028524

# Basic monitor setup
monitor = $monitor1, 2560x1440@120, 0x0, 1
monitor = $monitor2, 2560x1440@120, 2560x0, 1


# Default workspaces for monitors
# Set workspace 1 as the default for $monitor1
workspace = 1, monitor:$monitor1, default:true
workspace = 2, monitor:$monitor1
workspace = 3, monitor:$monitor1
workspace = 4, monitor:$monitor1
workspace = 5, monitor:$monitor1

# Set workspace 6 as the default for $monitor2
workspace = 6, monitor:$monitor2, default:true
workspace = 7, monitor:$monitor2
workspace = 8, monitor:$monitor2
workspace = 9, monitor:$monitor2
workspace = 10, monitor:$monitor2

