
# Ignore maximize requests from apps. You'll probably like this.
windowrule = suppressevent maximize, class:.*

# Fix some dragging issues with XWayland
windowrule = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0

# Fixes
windowrule = float, class:waypaper

#POB
windowrule = workspace special silent, class:pobfrontend
windowrule = tile, class:pobfrontend

#Awakened POE Trade
windowrule = float, class:awakened-poe-trade
windowrule = noblur, class:awakened-poe-trade
windowrule = noborder, class:awakened-poe-trade
windowrule = pin, class:awakened-poe-trade

#Steam Game
windowrulev2 = fullscreen,class:^steam_app\d+$
windowrulev2 = monitor 1,class:^steam_app_\d+$
windowrulev2 = workspace 20,class:^steam_app_\d+$
workspace = 20, border:false, rounding:false