
# Ignore maximize requests from apps. You'll probably like this.
windowrule = suppressevent maximize, class:.*

# Fix some dragging issues with XWayland
windowrule = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0

# Fixes
windowrule = float, class:waypaper

#POB
windowrule = workspace special silent, class:pobfrontend
windowrule = tile, class:pobfrontend

#Awakened POE Trade
windowrule = tag +apt, title:(Awakened PoE Trade)
windowrule = float, tag:apt 
windowrule = noblur, tag:apt
windowrule = nofocus, tag:apt # Disable auto-focus
windowrule = noshadow, tag:apt
windowrule = noborder, tag:apt
windowrule = size 100% 100%, tag:apt
windowrule = center, tag:apt

#Steam Game
windowrule = fullscreen,class:^steam_app\d+$
windowrule = monitor 1,class:^steam_app_\d+$
windowrule = workspace 20,class:^steam_app_\d+$
workspace = 20, border:false, rounding:false